- hosts: all
  become: yes
  tasks:
  - name: Update packages 
    ansible.builtin.apt:
      update_cache: yes 

  - name: Install unzip
    ansible.builtin.apt:
      name: unzip
      state: present

  - name: Install Mariadb and MariaDB-server
    ansible.builtin.apt:
      name:
      - mariadb-server
      state: present
  
  - name: Start MariaDB service
    ansible.builtin.service:
      name: mariadb
      state: started
      enabled: yes